services:
  - type: web
    name: telegram-bot
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: $BOT_TOKEN
      - key: WEBHOOK_URL
        value: $WEBHOOK_URL
    healthCheckPath: /health