services:
  - type: web
    name: telegram-bot
    runtime: docker
    env: docker
    plan: free
    region: frankfurt
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: TELEGRAM_BOT_TOKEN
        value: 7996792416:AAFGNZkdgemeWxqT7_JMVtsJxiIWf3TyQow